services:
  laravel:
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
    # container_name: hacksoft_laravel
    restart: unless-stopped
    working_dir: /var/www/html
    volumes: &laravel
      - ./laravel:/var/www/html
      - /var/www/html/vendor
      - ./laravel/storage:/var/www/html/storage
      - ./docker/php/entrypoint-laravel.sh:/usr/local/bin/entrypoint.sh:rw
    env_file:
      - ./laravel/.env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - network
    entrypoint: ["/usr/local/bin/entrypoint.sh"]

  worker:
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
    # container_name: hacksoft_worker
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    volumes: *laravel
    depends_on:
      - mysql
      - redis
    networks:
      - network
    entrypoint: ["/usr/local/bin/entrypoint.sh"]

  scheduler:
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
    # container_name: hacksoft_scheduler
    command: php artisan schedule:work
    volumes: *laravel
    depends_on:
      - mysql
      - redis
    networks:
      - network
    entrypoint: ["/usr/local/bin/entrypoint.sh"]

  mysql:
    image: mysql:8.0
    # container_name: hacksoft_mysql
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    # container_name: hacksoft_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - network

  nginx:
    image: nginx:alpine
    # container_name: hacksoft_nginx
    restart: unless-stopped
    ports:
      - "8009:80"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  mysql_data:
